import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./[components]/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex bg-gray-100 w-full flex-col items-center min-h-screen">
        <Header />
        <div className="core-container m-2">
        {children}
        </div>
      </body>
    </html>
  );
}
