import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./[components]/Header";
import Footer from "./[components]/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 w-full flex justify-between flex-col min-h-[100vh]">
        <span className="w-full flex flex-col items-center">
          <Header />
          <div className="core-container m-2">{children}</div>
        </span>
        <Footer />
      </body>
    </html>
  );
}
